In [1]:
import torch
import torch.nn as nn

In [2]:
a = torch.ones(2,2)
a

tensor([[1., 1.],
        [1., 1.]])

In [5]:
b= torch.randint(0,10,(2,2))
b

tensor([[1, 3],
        [1, 0]])

In [7]:
torch.add(a,b)

tensor([[2., 4.],
        [2., 1.]])

In [8]:
b.shape

torch.Size([2, 2])

In [10]:
b.reshape(-1).shape

torch.Size([4])

In [11]:
torch.tensor([4,2])

tensor([4, 2])

In [13]:
b.requires_grad_(True)

RuntimeError: only Tensors of floating point dtype can require gradients

In [35]:
x = torch.tensor([[1.,2.],[3.,4.]], requires_grad = True)

In [36]:
x

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [37]:
y = x**2 +1

In [38]:
z= y.mean()
z

tensor(8.5000, grad_fn=<MeanBackward0>)

In [39]:
z.backward()

In [40]:
x.grad

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [30]:
x

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [42]:
torch.cuda.is_available()

False

In [61]:
def forward(x, w):
    r  = w*x
    return r


In [62]:
def loss(y, y_pred):
    l = ((y-y_pred)**2).mean()
    return l

In [70]:
epoch = 100
lr = 0.02
x =torch.tensor([1,2,3,4,5], dtype= torch.float32)
y = torch.tensor([2,4,6,8,10], dtype = torch.float32)
w = torch.tensor(0, dtype = torch.float32, requires_grad = True)

for e in range(epoch):
    y_pred = forward(x, w)
    l = loss(y , y_pred)
    l.backward()
    with torch.no_grad():
        w -= lr*w.grad
    w.grad.zero_()
    if e%10 == 0:
        print(f'epoch: {e}, loss: {l}, w: {w}')

epoch: 0, loss: 44.0, w: 0.8799999952316284
epoch: 10, loss: 0.0004047722613904625, w: 1.996603012084961
epoch: 20, loss: 3.7037921618576775e-09, w: 1.9999897480010986
epoch: 30, loss: 0.0, w: 2.0
epoch: 40, loss: 0.0, w: 2.0
epoch: 50, loss: 0.0, w: 2.0
epoch: 60, loss: 0.0, w: 2.0
epoch: 70, loss: 0.0, w: 2.0
epoch: 80, loss: 0.0, w: 2.0
epoch: 90, loss: 0.0, w: 2.0


In [75]:

epoch = 100
lr = 0.02
x =torch.tensor([1,2,3,4,5], dtype= torch.float32)
y = torch.tensor([2,4,6,8,10], dtype = torch.float32)
w = torch.tensor(0, dtype = torch.float32, requires_grad = True)
loss = nn.MSELoss()
optim = torch.optim.SGD([w], lr =lr )
def forward(x):
    r  = w*x
    return r

for e in range(epoch):
    y_pred = forward(x)
    l = loss(y , y_pred)
    l.backward()
    optim.step()
    optim.zero_grad()
    if e%10 == 0:
        print(f'epoch: {e}, loss: {l}, w: {w}')

epoch: 0, loss: 44.0, w: 0.8799999952316284
epoch: 10, loss: 0.0004047722613904625, w: 1.996603012084961
epoch: 20, loss: 3.7037921618576775e-09, w: 1.9999897480010986
epoch: 30, loss: 0.0, w: 2.0
epoch: 40, loss: 0.0, w: 2.0
epoch: 50, loss: 0.0, w: 2.0
epoch: 60, loss: 0.0, w: 2.0
epoch: 70, loss: 0.0, w: 2.0
epoch: 80, loss: 0.0, w: 2.0
epoch: 90, loss: 0.0, w: 2.0


In [86]:
x = torch.tensor([[1],[2], [3], [4]], dtype = torch.float32)
y = torch.tensor([[2], [4], [6], [8]], dtype = torch.float32)
epoch = 101
lr = 0.1
n_sample, n_features = x.shape
model = nn.Linear(n_features, n_features)
loss = nn.MSELoss()
optim = torch.optim.SGD(model.parameters(), lr = lr)


for e in range(epoch):
    y_pred = model(x)
    l = loss(y_pred, y)
    l.backward()
    optim.step()
    optim.zero_grad()
    if e%10==0:
        [w, b] = model.parameters()
        print(f'epoch: {e}, loss: {l}, w: {w[0][0]}')

epoch: 0, loss: 13.676753997802734, w: 2.7837259769439697
epoch: 10, loss: 0.005212053656578064, w: 1.9940742254257202
epoch: 20, loss: 0.0003607481485232711, w: 1.9849683046340942
epoch: 30, loss: 0.00019559597421903163, w: 1.9887137413024902
epoch: 40, loss: 0.00010649901378201321, w: 1.991668462753296
epoch: 50, loss: 5.798523488920182e-05, w: 1.9938520193099976
epoch: 60, loss: 3.1571682484354824e-05, w: 1.9954636096954346
epoch: 70, loss: 1.719064312055707e-05, w: 1.9966527223587036
epoch: 80, loss: 9.359611794934608e-06, w: 1.9975299835205078
epoch: 90, loss: 5.096231234347215e-06, w: 1.9981775283813477
epoch: 100, loss: 2.775008852040628e-06, w: 1.998655080795288


4 1


In [ ]:
model = nn.Linear()